package pe.ceps.uni.arregloapp.view;

import javax.swing.JOptionPane;
import pe.ceps.uni.arregloapp.service.ArregloService;

public class ArregloView extends javax.swing.JFrame {

  /**
   * Creates new form ArregloView
   */
  public ArregloView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    txtArreglo = new javax.swing.JTextArea();
    btnGenerar = new javax.swing.JButton();
    btnEstadistica = new javax.swing.JButton();
    txtNum = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    txtArreglo.setEditable(false);
    txtArreglo.setColumns(20);
    txtArreglo.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
    txtArreglo.setRows(5);
    jScrollPane1.setViewportView(txtArreglo);

    btnGenerar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
    btnGenerar.setText("Generar");
    btnGenerar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGenerarActionPerformed(evt);
      }
    });

    btnEstadistica.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
    btnEstadistica.setText("Estdistica");
    btnEstadistica.setEnabled(false);
    btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEstadisticaActionPerformed(evt);
      }
    });

    txtNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txtNum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor de N", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 0, 204))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnEstadistica, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
          .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(txtNum))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(62, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
    // Datos
    int num = Integer.parseInt(txtNum.getText());
    // Proceso
    int arreglo[] = ArregloService.crearArreglo(num);
    // Reporte
    txtArreglo.setText("");
    for (int dato : arreglo) {
      txtArreglo.append(String.valueOf(dato) + "\n");
    }
    btnEstadistica.setEnabled(true);
            
  }//GEN-LAST:event_btnGenerarActionPerformed

  private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed
    // Variable
    String repo = "";
    // Proceso
    repo += "Mayor: " + ArregloService.leerMayorV1() + "\n";
    repo += "Menor: " + ArregloService.leerMenorV1()+ "\n";
    // Reporte
    JOptionPane.showMessageDialog(rootPane, repo);
  }//GEN-LAST:event_btnEstadisticaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ArregloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ArregloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ArregloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ArregloView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ArregloView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnEstadistica;
  private javax.swing.JButton btnGenerar;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txtArreglo;
  private javax.swing.JTextField txtNum;
  // End of variables declaration//GEN-END:variables
}
